controllers-films-users
NovikSerg88/java-filmorate pull request #2
Opened 2023-04-28 10:54 UTC by NovikSerg88

2023-04-28 21:22 UTC, sergeymamonov requested changes

2023-04-28 21:22 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Лучше не писать конструкторы руками, а пользоваться аннотациями Lombok, например AllArgsContstructor.

2023-04-28 21:22 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> getAllFilms() {
Collection - это слишком общий интерфейс, то есть здесь может вернуться и лист, и очередь.

2023-04-29 00:51 UTC, NovikSerg88 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Добавил конструктор через аннотацию @AllArgsConstructor

2023-04-29 00:52 UTC, NovikSerg88 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> getAllFilms() {
Заменил на List<>. Доработал методы.

2023-04-29 05:45 UTC, sergeymamonov approved these changes

2023-04-29 06:12 UTC, merged