Sprint 10: Add friends likes
NovikSerg88/java-filmorate pull request #3
Opened 2023-05-05 11:07 UTC by NovikSerg88

feat: add-friends-likes

2023-05-06 12:45 UTC, sergeymamonov requested changes

2023-05-06 12:45 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
>  class FilmorateApplicationTests {
В строке 90 можно проще "q".repeat(число)

2023-05-06 12:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (id <= 0) {
Эту валидацию лучше перенести в сервис.

2023-05-06 12:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (id <= 0) {
Место валидации в сервисе.

2023-05-06 12:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (id <= 0) {
В сервис.

2023-05-06 12:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectParameterException.java
> +    public String getParameter() {
Геттер где-то используется?

2023-05-06 12:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return -1 * comp;
Лучше избавиться от -1. Попробуйте поменять местами p0 и p1 в компараторе (строка 51).

2023-05-06 12:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        List<Film> allFilms = new ArrayList<>();
попробуйте return new ArrayList<>(films.entrySet());

2023-05-07 02:08 UTC, NovikSerg88 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
>  class FilmorateApplicationTests {
Заменил на "a".repeat(201)

2023-05-07 02:08 UTC, NovikSerg88 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (id <= 0) {
Перенес в сервис

2023-05-07 02:09 UTC, NovikSerg88 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (id <= 0) {
Перенес в сервис

2023-05-07 02:17 UTC, NovikSerg88 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (id <= 0) {
Перенес в сервис

2023-05-07 02:30 UTC, NovikSerg88 commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectParameterException.java
> +    public String getParameter() {
Добавлен вызов параметра в обработчике исключения

2023-05-07 02:35 UTC, NovikSerg88 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return -1 * comp;
(p0, p1) -> p1.getCount().compareTo(p0.getCount())

2023-05-07 02:56 UTC, NovikSerg88 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        List<Film> allFilms = new ArrayList<>();
return new ArrayList<>(films.values());

2023-05-07 19:55 UTC, sergeymamonov approved these changes

2023-05-08 06:48 UTC, merged